### ISSUE TITLE
Google flu paper link in lecture 2?

### ISSUE THREAD

**Issue by rusincovitch** [Duke-Translational-Bioinformatics/mmci-practical-datascience#1]
I think that there might be an incorrect URL listed in the [lecture 2 readings](https://github.com/Duke-Translational-Bioinformatics/mmci-practical-datascience/tree/master/lecture02_170526)?

Current listing:
The Parable of Google Flu: Traps in Big Data Analysis. David Lazer, Ryan Kennedy, Gary King, and Alessandro Vespignani. Science, 2014 vol. 343 (6176) pp. 1203-1205. http://ieeexplore.ieee.org/document/6113109/

But I think this perhaps was intended to be:
http://science.sciencemag.org/content/343/6176/1203.long
?

**Comment by erichhuang** [comment]
Fixed
