### ISSUE TITLE
Oxford Style Debate Topics

### ISSUE THREAD

**Issue by benneely** [Duke-Translational-Bioinformatics/mmci-practical-datascience#10]
Please help me think of some topics

**Comment by crdennis0929** [comment]
EHRs of the future will function primarily as platforms using FHIR to run services

**Comment by grant021** [comment]
API's will not improve sharing of heath data.

**Comment by neilray** [comment]
National Patient ID are essential for successful interoperability

**Comment by benneely** [comment]
Healthcare is shifting from the inpatient setting to the outpatient setting, and technology is at the forefront of this change.

**Comment by benneely** [comment]
AI/Machine learning/Deep learning has no place in health care.

**Comment by benneely** [comment]
Leaders of technology companies should be on hospital boards or serve as hospital administrators.

**Comment by benneely** [comment]
De-identified EHR data should be made more easily-accessible for research and quality improvement projects.

**Comment by benneely** [comment]
Is there a difference in research populations when comparing traditional clinical research subjects and new methods of recruiting clinical research subjects through online methods?

**Comment by benneely** [comment]
Compliance to the research guidelines among the different populations?

**Comment by benneely** [comment]
Are new CMS programs affecting the triple aim? ACO, Medicare Advantage, CCJR.

**Comment by benneely** [comment]
Resolved; that access to digital technology is integral to quality healthcare; therefore, patients who cannot afford smartphones should be provided with them.

**Comment by benneely** [comment]
Is their still a need for HIPPA Protections in the electronic interoperability of health information exchange.

**Comment by benneely** [comment]
Machine Learning and AI will fully replace the need for physicians in <x> years (I'd say 50)

**Comment by benneely** [comment]
EHRs, such as Epic and Cerner, will never be truly open sourced.

**Comment by benneely** [comment]
The ever-changing regulations in healthcare restrict health systems from focusing on newer, advanced technology (e.g. AI) that can more rapidly improve outcomes, and instead force them to simply prove compliance to reactive quality measures.

**Comment by benneely** [comment]
Opt-out vs. Opt-in policy in sharing your own health data.

**Comment by benneely** [comment]
As medicine becomes more and more automated healthcare practitioners must continue training and practice related to practicing medicine without automated systems so that in the advent of catastrophic failure they will be able to come to aid of the public.  IE in events were the systems are overwhelmed because of a massive influx of patients or all power is lost as in hurricanes.  Should there be dedicated time, periodically above and beyond simple CME?

**Comment by benneely** [comment]
Patient privacy is inhibiting innovation.

**Comment by benneely** [comment]
That block chain technology is the solution to interoperability and data security problems in healthcare.

**Comment by benneely** [comment]
The federal government should mandate that patients be given ownership/control of their medical data.

**Comment by MARCXAVIER** [comment]
Is EHR actually effective?

**Comment by laiweihong** [comment]
Will AI lower the healthcare costs in the US?

http://www.newsweek.com/2017/06/02/ai-cure-america-sick-health-care-system-614583.html
