### ISSUE TITLE
Machine Learning Score Error

### ISSUE THREAD

**Issue by armandobedoya** [Duke-Translational-Bioinformatics/mmci-practical-datascience#18]
I get this error. anyone know how to fix this? looks like there is problem with the credentials i provided.

{
    "data": {
        "error": {
            "code": "Unauthorized",
            "message": "Request is unauthorized to access resource.",
            "details": [
                {
                    "code": "ScoreRequestUnauthorized",
                    "message": "Invalid credentials provided."
                }
            ]
        }
    },
    "status": 401,
    "config": {
        "method": "POST",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "jsonpCallbackParam": "callback",
        "data": {
            "url": "https://ussouthcentral.services.azureml.net/workspaces/e1359f3daa81421797c435961da55cf4/services/1ae0b4d907c34d9fa43a9cdde3daf4a7/jobs",
            "apikey": "f50MQMYMN//+Ceg2yBpSbYlDzVJa+bsyc+g26afsaJwaeAptsZeToOyQp8MY2ZeOg8fPtjVpIF1JrKWJ9QrNUw==",
            "scoredvariablename": "Scored Probabilities",
            "datascientist": "Armando Sweet Pea Bedoya"
        },
        "url": "/api/azure/",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8"
        }
    },
    "statusText": "Unauthorized"
}

**Comment by benneely** [comment]
Looks like the url/apikey combination is not valid. Go back to the `WebServices` portion of Azure Machine Learning Studio and ensure that the information within the `batch` portion of your web services match what is in the Google Spreadsheet.

**Comment by benneely** [comment]
Closing this issue - if it is still a problem, please create a new issue on the application repo (https://github.com/Duke-Translational-Bioinformatics/mmci-practical-datascience-competition) , and I will continue to help.
