### ISSUE TITLE
Error. I keep on getting this message:

### ISSUE THREAD

**Issue by MARCXAVIER** [Duke-Translational-Bioinformatics/mmci-practical-datascience#19]
{
    "data": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n",
    "status": 504,
    "config": {
        "method": "POST",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "jsonpCallbackParam": "callback",
        "data": {
            "url": "https://ussouthcentral.services.azureml.net/workspaces/2eac2d66bd4d448c848fa9eaae108a95/services/2234764a8f944448856cebf2122e18d8/jobs",
            "apikey": "P0FqJOD0OJIVU9c7oaTaHPIJ/W79MODXQRSkDtybf1oG2N9u5hvs9oeJwm/Kw0Een2+GyxPNXGj6SgLBoqF9bA==",
            "scoredvariablename": "Scored Probabilities",
            "datascientist": "Marc Xavier"
        },
        "url": "/api/azure/",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8"
        }
    },
    "statusText": "Gateway Time-out"
}

**Comment by benneely** [comment]
This is an issue with overloading the server - need to reconfigure the deployment stack to handle larger traffic loads. Closing here and moving to the application repo (https://github.com/Duke-Translational-Bioinformatics/mmci-practical-datascience-competition)
