### ISSUE TITLE
Debate bracket

### ISSUE THREAD

**Issue by tks15** [Duke-Translational-Bioinformatics/mmci-practical-datascience#24]
Here is a bracket for the debate, if you want to use it.
[MMCi_2017_DebateBracket.xlsx](https://github.com/Duke-Translational-Bioinformatics/mmci-practical-datascience/files/1140543/MMCi_2017_DebateBracket.xlsx)

**Comment by slwhiting** [comment]
Thanks for putting this together! Super helpful!!

See you next week  . . .

Steff

**Comment by erichhuang** [comment]
Yup. This looks right. Thanks for doing this!
